# Workflow name
name: Run storybook tests locally

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'master'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Storybook tests
        run: yarn test-storybook:ci
        continue-on-error: true
      - name: Bundle failed Snapshots
        run: |
          mkdir snapshots
          powershell -Command "Get-ChildItem -Recurse -Filter *.png | ForEach-Object { Copy-Item $_ -Destination snapshots }"
      - name: Upload failed snapshot images
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-images
          path: snapshots/
